import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/nav";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/components/modals/modal-provider";
import { SessionProvider } from "@/components/providers/session-provider";



export const metadata: Metadata = {
  title: "Everything design store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <SessionProvider>
          <ModalProvider />
          <Navbar />
          {children}
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
